In [1]:
from numpy import array

In [2]:
a = array([[ 0, 1, 2, 3, 4, 5],
           [10,11,12,13,14,15],
           [20,21,22,23,24,25],
           [30,31,32,33,34,35],
           [40,41,42,43,44,45],
           [50,51,52,53,54,55]])

In [3]:
import numpy as np

In [4]:
a[2,3]

23

In [5]:
#第一行
a[0]

array([0, 1, 2, 3, 4, 5])

In [7]:
#第一列
a[:,0]

array([ 0, 10, 20, 30, 40, 50])

In [8]:
a[3,:]

array([30, 31, 32, 33, 34, 35])

In [9]:
a[3,2:4]

array([32, 33])

In [10]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [11]:
a[::2,::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [22]:
a[(0,2,3),::2]

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [13]:
a.max()

55

In [14]:
a.sum()

990

In [15]:
a.mean()

27.5

In [33]:
a=np.zeros((15,15),dtype=float)

In [24]:
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [27]:
a.any()

False

In [28]:
a[0,0]=1

In [29]:
#a里存在1
a.any()

True

In [38]:
#快速生成数组
c = np.arange(1,10)
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
b = np.zeros([5,5])

In [36]:
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [39]:
#0-100，5等分的数组，默认浮点数
b = np.linspace(0,100,5)
b

array([  0.,  25.,  50.,  75., 100.])